version: '2.0'

services:
  nginx: 
    #image: nginx:latest
    image: nginx:1.15.8
    #image: nginx:alpine
    #image: rproxy
    container_name: production_nginx
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"    
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx.setting.conf:/etc/nginx/nginx.setting.conf
      - ./conf/common1.conf:/etc/nginx/common1.conf
      - ./conf/common2.conf:/etc/nginx/common2.conf
      - ./cert/cuckoo.com.crt:/etc/ssl/cuckoo.com.crt
      - ./cert/cuckoo.com.key:/etc/ssl/cuckoo.com.key
        
      - cachedata:/var/cache/nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    cpu_shares: 100 #1 core
    mem_limit: 1G

volumes:
  cachedata:
    driver: local
