- name: apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common is present 
  apt:
    name: '{{ packages }}'
    state: present
    force: yes 
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common 
  tags: [docker-ce common]
  
- name: Add an Apt signing key to a specific keyring file
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

    
- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes
    state: present
  tags: [docker-ce common]
  
#sudo apt-get remove docker docker-engine docker.io  
#sudo apt-get remove docker-ce docker-ce-cli containerd.io

- name: docker-ce, docker-ce-cli, containerd.io is present 
  apt:
    name: '{{ packages }}'
    state: present
    force: yes 
    update_cache: yes
  vars:
    packages:
      - 'docker-ce={{docker_install_ver}}'
      - 'docker-ce-cli={{docker_install_ver}}'
      - containerd.io  
  tags: [docker-ce common]

- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.11.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    timeout: 60
  tags: [docker-ce common]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker-ce common]
