apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx-dp
    spec:
      containers:
      - name: my-nginx-dp
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: my-nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    run: my-nginx-dp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx-svc
          servicePort: 80