apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: customer-dp
    spec:
      containers:
      - name: customer-dp
        image: choonhow/customer:0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  labels:
    app: customer-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    run: customer-dp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customer-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app
        backend:
          serviceName: customer-svc
          servicePort: 8080