
- name:      Join Kubernetes Cluster
  become:    true
  shell:     kubeadm join --token={{ kubeadm_token }} {{ kubernetes_master_ip }}:6443 --discovery-token-unsafe-skip-ca-verification 
  register: ps
- debug: var=ps.stdout_lines